# Infra CI/CD (approval based)..............
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: hashicorp/terraform:1.6
    entrypoint: sh
    dir: gcp-devops/infra
    args:
      - -c
      - terraform init

  - name: hashicorp/terraform:1.6
    entrypoint: sh
    dir: gcp-devops/infra
    args:
      - -c
      - terraform fmt -check

  - name: hashicorp/terraform:1.6
    entrypoint: sh
    dir: gcp-devops/infra
    args:
      - -c
      - terraform validate

  - name: hashicorp/terraform:1.6
    entrypoint: sh
    dir: gcp-devops/infra
    args:
      - -c
      - terraform plan

  - name: hashicorp/terraform:1.6
    entrypoint: sh
    dir: gcp-devops/infra
    args:
      - -c
      - terraform apply -auto-approve