# Infra CI/CD (approval based)..............
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: hashicorp/terraform:1.6
    entrypoint: sh
    dir: Terra_V1/gcp-devops/infra
    args:
      - -c
      - |
          terraform init -reconfigure -input=false
          terraform destroy -auto-approve