# Infra CI/CD (approval based).................
steps:
  - name: hashicorp/terraform:1.6
    entrypoint: sh
    dir: Terra_V1/gcp-devops/infra/terraform
    args:
      - -c
      - terraform init

  - name: hashicorp/terraform:1.6
    entrypoint: sh
    dir: Terra_V1/gcp-devops/infra/terraform
    args:
      - -c
      - terraform fmt -check

  - name: hashicorp/terraform:1.6
    entrypoint: sh
    dir: Terra_V1/gcp-devops/infra/terraform
    args:
      - -c
      - terraform validate

  - name: hashicorp/terraform:1.6
    entrypoint: sh
    dir: Terra_V1/gcp-devops/infra/terraform
    args:
      - -c
      - terraform plan

  - name: hashicorp/terraform:1.6
    entrypoint: sh
    dir: Terra_V1/gcp-devops/infra/terraform
    args:
      - -c
      - terraform apply -auto-approve

